nome = str(input('digite seu nome completo: '))
maiuscula = nome.upper()
minuscula = nome.lower()
num_letras = len(nome) - nome.count(' ')
num_primeiro = nome.split()
print('Seu nome em maiuscula é: {}'.format(maiuscula))
print('Seu nome em minuscula é: {}'.format(minuscula))
print('Seu nome tem ao todo {} letras'.format(num_letras))
print('Seu primeiro nome tem {} letras'.format(len(num_primeiro[0])))